project:
  type: website

website:
  title: "Markus Ljungqvist"
  search: false
  navbar:
    background: primary
    pinned: true
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: tools.qmd
        text: Tools
      - href: theses.qmd
        text: Theses

format:
  html:
    minimal: true
    theme:
      - darkly
      - style.scss
    css: styles.css
    toc: false
