project:
  type: website

website:
  title: "Markus Ljungqvist"
  site-url: https://MarkusLjungqvist.com
  search: false
  page-footer: 
    border: false
    background: $black
    foreground: $blue
    left: "[Source Code](https://codeberg.org/mackan/pages)"
  navbar:
    background: $black
    foreground: $white
    pinned: true
    collapse: false
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: tools.qmd
        text: Tools
      - href: theses.qmd
        text: Theses

format:
  html:
    minimal: true
    theme:
      - darkly
      - style.scss
    css: styles.css
    toc: false
