project:
  type: website
  output-dir: docs

website:
  title: "Mackrics"
  site-url: "https://mackrics.com"
  search: false
  navbar:
    title: false
    background: $black
    foreground: $white
    alignment: center
    pinned: true
    collapse: false
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: envelope-at
        href: mailto:mackrics@pm.me
        aria-label: Mail
      - icon: key
        href: ./publickey.txt
        aria-label: PGP key
      - icon: rss
        href: ./index.xml
        aria-label: RSS feed
      - icon: github
        href: https://github.com/mackrics
        aria-label: GitHub
      - icon: mastodon
        href: https://fosstodon.org/@mackan
        rel: me
        aria-label: Mastodon
format:
  html:
    minimal: true
    theme:
      - darkly
      - style.scss
    monofont: "IBM Plex Mono"
    css: styles.css
    toc: false
    highlight-style: ctp-mocha.theme
