project:
  type: website
  output-dir: docs

website:
  title: "Markus Ljungqvist"
  site-url: "https://mackrics.com"
  search: false
  favicon: ./media/profile_picture.png
  page-footer: 
    border: false
    background: $black
    foreground: $blue
    left: "[Source Code](https://github.com/Mackrics/mackrics.github.io)"
  navbar:
    title: false
    background: $black
    foreground: $white
    alignment: center
    pinned: true
    collapse: false
    left:
      - href: index.qmd
        text: About
      - href: writing.qmd
        text: Writing
    right:
      - icon: envelope
        href: mailto:Markus@Ljungqvist.xyz
        aria-label: Mail
      - icon: key
        href: ./publickey.txt
        aria-label: PGP key
      - icon: rss
        href: https://mackrics.com/blog/index.xml
        aria-label: RSS feed
      - icon: github
        href: https://github.com/mackrics
        aria-label: GitHub
      - icon: mastodon
        href: https://fosstodon.org/@mackan
        rel: me
        aria-label: Mastodon
format:
  html:
    minimal: true
    theme:
      - darkly
      - style.scss
    css: styles.css
    toc: false
