project:
  type: website
  output-dir: docs

website:
  title: "Markus Ljungqvist"
  site-url: https://mackrics.com
  search: false
  favicon: ./media/profile_picture.png
  page-footer: 
    border: false
    background: $black
    foreground: $blue
    left: "[Source Code](https://codeberg.org/mackan/pages)"
  navbar:
    title: false
    background: $black
    foreground: $white
    alignment: center
    pinned: true
    collapse: false
    left:
      - href: index.qmd
        text: About
      - href: tools.qmd
        text: Tools
      - href: writing.qmd
        text: Writing

format:
  html:
    minimal: true
    theme:
      - darkly
      - style.scss
    css: styles.css
    toc: false
